- 05-file-transfer-cloud/README.md
- 05-file-transfer-cloud/terraform/main.tf
- 05-file-transfer-cloud/terraform/test-document.txt
Fixes the errors in sample 5's Terraform script. Updates the providers and adds the missing test file.
- updated the catalog request URI in the `README`, as it was outdated and returned 404
- updated the `curl` command for initiating a negotiation, as this previously said to copy a policy from sample 4 (in which case the contract request would be superfluous)
Closes #3
> fix(Sample5): fix terraform errors

- transfer/transfer-07-provider-push-http/README.md
fix the port values of `Provider` and `Consumer` in README
Match the port values in the configuration properties to the README
Closes #38
> fix: port values in the `README` in transfer-07

- settings.gradle.kts
stick version catalog to version `milestone-9`
avoid compilation break
- likely we'll need to use version catalog in this project as well
Closes #43
> fix: stick to milestone8 version for catalog

- .github/workflows/verify.yaml
- gradle/wrapper/gradle-wrapper.properties
Bump gradle-wrapper to 7.6.1
Avoid conflicts with jackson 2.15.0
- add a "build" CI job to test out the whole project build status
- removed an useless gatling upload job
Closes #45 
Closes #48
> build(deps): bump gradle-wrapper to 7.6.1

- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- other/custom-runtime/build.gradle.kts
- settings.gradle.kts
- transfer/transfer-06-consumer-pull-http/README.md
- transfer/transfer-06-consumer-pull-http/http-pull-connector/build.gradle.kts
- transfer/transfer-07-provider-push-http/README.md
- transfer/transfer-07-provider-push-http/http-push-connector/build.gradle.kts
Add libs.versions.toml file to declare dependencies.
Update gradle version
Rename .jar for samples - transfer-06-consumer-pull-http, transfer-07-provider-push-http
Renaming of .jar for the above mentioned samples were done to resolve the issue: problems found with the configuration of task shadowJar
> build: add libs.versions.toml for samples

- transfer/transfer-01-file-transfer/contractoffer.json
- transfer/transfer-01-file-transfer/filetransfer.json
- transfer/transfer-04-open-telemetry/filetransfer.json
- transfer/transfer-05-file-transfer-cloud/README.md
- transfer/transfer-06-consumer-pull-http/README.md
- transfer/transfer-07-provider-push-http/README.md
Set the explicit context for ODRL to avoid http calls for a remote context
fiix samples
- "inlined" the `properties` field of `dataAddress`, because it will disappear with the new EDC version.
Closes #63
Closes #64
Closes #67
> fix: set explicit context for ODRL

- system-tests/src/test/java/org/eclipse/edc/samples/transfer/FileTransferSampleTestCommon.java
- transfer/transfer-02-file-transfer-listener/README.md
- transfer/transfer-04-open-telemetry/README.md
- transfer/transfer-05-file-transfer-cloud/README.md
Update paths to v2 that stayed behind during the update to v 0.1.0
fix samples
Closes #68
Closes #69
> fix: adapt paths to v2

- transfer/transfer-07-provider-push-http/README.md
documentation had some invalid JSON body for the register data plane command in `transfer-07-provider-push-http`, fixed it here
Closes #94
> docs: fixed curl command in provider push README

- build.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
Centralizes EDC version number.
refactoring
Closes #109 
> refactor: centralize EDC version

- basic/basic-03-configuration/README.md
- transfer/transfer-01-file-transfer/README.md
- transfer/transfer-04-open-telemetry/README.md
- transfer/transfer-04-open-telemetry/contractoffer.json
- transfer/transfer-04-open-telemetry/docker-compose.yaml
- transfer/transfer-06-consumer-pull-http/README.md
- transfer/transfer-06-consumer-pull-http/http-pull-consumer/consumer-configuration.properties
- transfer/transfer-06-consumer-pull-http/http-pull-provider/provider-configuration.properties
- transfer/transfer-07-provider-push-http/README.md
- transfer/transfer-07-provider-push-http/http-push-connector/build.gradle.kts
- transfer/transfer-07-provider-push-http/http-push-consumer/consumer-configuration.properties
- transfer/transfer-07-provider-push-http/http-push-provider/provider-configuration.properties
remove the leftovers of IDS dependencies and replace them with DSP . 
remove the IAIS dependency . 
The IDS is no longer needed
refers #103 
> docs: IDS cleanup and replace with DSP

- transfer/transfer-06-consumer-pull-http/http-pull-connector/build.gradle.kts
Add edc-control-plane-api-client to resolve boot issue when running the jar for transfer-06-consumer-pull-http
When running the jar following issues was coming:
org.eclipse.edc.spi.system.injection.EdcInjectionException: The following injected fields were not provided:
Field "transferProcessApiClient" of type [interface org.eclipse.edc.connector.api.client.spi.transferprocess.TransferProcessApiClient] required by org.eclipse.edc.connector.dataplane.framework.DataPlaneFrameworkExtension
To resolve it edc-control-plane-api-client is added as dependency
Closes # <-- [_insert Issue number if one exists_](https://github.com/eclipse-edc/Connector/discussions/3436)
> fix: add missing edc-control-plane-api-client dependency

- transfer/transfer-06-consumer-pull-http/README.md
- Setting up a data plane on the consumer is not required, both sink and source are on the provider side
- Coherent case for paragraph titles
README for consumer-pull http transfer updated.
To provide a leaner setup configuration.
> docs: consumer-pull transfer README update

- transfer/transfer-07-provider-push-http/README.md
- transfer/transfer-07-provider-push-http/http-push-connector/build.gradle.kts
add missing edc-control-plane-api-client dependency
> fix: add missing edc-control-plane-api-client dependency (#134)

- transfer/transfer-00-prerequisites/README.md
fix the invalid command line of [README of transfer-00-prerequisites](https://github.com/eclipse-edc/Samples/tree/e9e41d5bdd56a2411fa2d462189faa0480ffe811/transfer/transfer-00-prerequisites#3-register-data-plane-instance-for-provider).
extra `|` before `-s` causes error on copying from browser and pasting.
```
$ curl -H 'Content-Type: application/json' \
-d @transfer/transfer-00-prerequisites/resources/dataplane/register-data-plane-provider.json \
-X POST "http://localhost:19193/management/v2/dataplanes" | -s | jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 19193 after 0 ms: Connection …
```
> docs: fix invalid command line in the README of transfer-00-prerequisites

- CONTRIBUTING.md
- README.md
fixes a link
because it was wrong
> fix(docs): change contributing.md link to correct one

- .github/workflows/verify.yaml
- gradle/libs.versions.toml
- settings.gradle.kts
- system-tests/build.gradle.kts
- system-tests/src/test/java/org/eclipse/edc/samples/common/FileTransferCommon.java
- system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/KafkaSaslContainer.java
- system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming03KafkaToKafkaTest.java
- transfer/streaming/streaming-03-kafka-broker/1-asset.json
- transfer/streaming/streaming-03-kafka-broker/2-policy-definition.json
- transfer/streaming/streaming-03-kafka-broker/3-contract-definition.json
- transfer/streaming/streaming-03-kafka-broker/4-get-dataset.json
- transfer/streaming/streaming-03-kafka-broker/5-negotiate-contract.json
- transfer/streaming/streaming-03-kafka-broker/6-transfer.json
- transfer/streaming/streaming-03-kafka-broker/README.md
- transfer/streaming/streaming-03-kafka-broker/kafka-config/admin.properties
- transfer/streaming/streaming-03-kafka-broker/kafka.env
- transfer/streaming/streaming-03-kafka-broker/kafka_broker_jaas.conf
- transfer/streaming/streaming-03-kafka-broker/streaming-03-runtime/build.gradle.kts
- transfer/streaming/streaming-03-kafka-broker/streaming-03-runtime/consumer.properties
- transfer/streaming/streaming-03-kafka-broker/streaming-03-runtime/provider.properties
- transfer/streaming/streaming-03-kafka-broker/streaming-03-runtime/src/main/java/org/eclipse/edc/samples/streaming/KafkaExtension.java
- transfer/streaming/streaming-03-kafka-broker/streaming-03-runtime/src/main/java/org/eclipse/edc/samples/streaming/KafkaToKafkaDataFlowController.java
- transfer/streaming/streaming-03-kafka-broker/streaming-03-runtime/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
Adds a streaming kafka-broker sample, that shows how to stream data through EDC with a custom `DataFlowController` without using the data-plane.
streaming
- removed the `Checkstyle` job in the ci as `Build` already runs checkstyle
- cleanup `FileTransferCommon`, that contained a lot of unused methods
Closes #150 
> feat: provide kafka-broker transfer streaming sample

- transfer/transfer-05-file-transfer-cloud/cloud-transfer-consumer/build.gradle.kts
- transfer/transfer-05-file-transfer-cloud/transfer-file-cloud/build.gradle.kts
This PR adds dependencies on the "transfer/transfer-05-file-transfer-cloud/cloud-transfer-consumer/build.gradle.kts" and "transfer/transfer-05-file-transfer-cloud/transfer-file-cloud/build.gradle.kts"
This dependencies are added because there was an error when trying to run the jar file.
[Linked Discussion](https://github.com/eclipse-edc/Samples/discussions/174)
> build: Dependency Correction on Cloud Transfer Sample

- advanced/advanced-01-open-telemetry/resources/negotiate-contract.json
- system-tests/src/test/java/org/eclipse/edc/samples/common/NegotiationCommon.java
- system-tests/src/test/java/org/eclipse/edc/samples/util/TransferUtil.java
- transfer/transfer-01-negotiation/README.md
- transfer/transfer-01-negotiation/resources/negotiate-contract.json
Add missing description on the transfer 01 sample
Closes #190 
> fix: add missing detail in transfer-01

- transfer/transfer-02-consumer-pull/README.md
- changed the command for requesting data with the token to target the provider instead of the consumer
The change reflects what already written in the README file as well as the [documentation in the Connector repo](https://github.com/eclipse-edc/Connector/blob/main/docs/developer/data-transfer.md#consumer-pull).
> docs: updated README.md for transfer-02-consumer-pull

- README.md
- advanced/advanced-01-open-telemetry/README.md
updated description about required Java version in the README.
[Java 17 is required](https://github.com/eclipse-edc/GradlePlugins/blob/v0.5.1/plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/JavaConvention.java#L30) now instead of Java 11.
Closes #231
> fix: update description about required Java version

- transfer/transfer-04-event-consumer/consumer-with-listener/build.gradle.kts
"transfer/transfer-04-event-consumer/consumer-with-listener/build.gradle.kts" modified:
"libs.edc.control.plane.api" added
"libs.edc.control.plane.api" duplication eliminated
We were running the guide examples and we wanted to reuse the connector.jar of "transfer-04-event-consumer" to all cases, but when we run the "Simple Provider push Http transfer flow" example we noticed that a 404 error appeared.
Comparing gradles we noticed that exists a duplicated and missing import in the 04 version. We copied the same imports from version 00 to 04 and all worked.
_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull …
> fix: build.gradle.kts imports fixed

- transfer/README.md
- transfer/transfer-05-file-transfer-cloud/README.md
- transfer/transfer-05-file-transfer-cloud/cloud-transfer-consumer/build.gradle.kts
- transfer/transfer-05-file-transfer-cloud/cloud-transfer-consumer/config.properties
- transfer/transfer-05-file-transfer-cloud/cloud-transfer-provider/build.gradle.kts
- transfer/transfer-05-file-transfer-cloud/cloud-transfer-provider/config.properties
updates the provider/consumer configurations, builds and README for transfer-05-file-transfer-cloud
Sample is out of date.
Closes [Issue fetching Retrieve provider Contract Offers](https://github.com/eclipse-edc/Samples/issues/236)
> fix: update transfer-05-file-transfer-cloud sample

- basic/basic-01-basic-connector/build.gradle.kts
Adds the `http` dependency to the basic-01 runtime.
to keep it alive at startup, because the other dependencies (`boot` and `connector-core`) don't provide separated thread operations.
- maybe `boot` module should provide something that keeps the runtime alive until it gets shot down.
Closes #303 
> fix: add dependency to keep runtime alive

- basic/basic-03-configuration/README.md
Remove the appendix about management-api because it's out of scope with the sample and it can get stale (as happened in #321 ).
Management API is already involved in `transfer` samples
_Briefly state why the change was necessary._
Closes #321 
> docs: remove management api appendix from basic-03

- system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming01httpToHttpTest.java
- system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/StreamingParticipant.java
- transfer/streaming/streaming-01-http-to-http/negotiate-contract.json
- transfer/streaming/streaming-01-http-to-http/transfer.json
Fixes issues #244 and #334 for sample transfer/streaming/streaming-01-http-to-http
- Missing `assigner` field in contract request
- Missing `transferType` in transfer request
- Did not use JSON files in testcase
Sample can not be executed completely.
Closes #244 
Closes #334
> fix: add missing json fields for sample streaming http-to-http 

- system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming03KafkaToKafkaTest.java
- transfer/streaming/streaming-03-kafka-broker/5-negotiate-contract.json
- transfer/streaming/streaming-03-kafka-broker/6-transfer.json
Issues around running streaming-03-kafka-broker sample. Issues with contract negotiation and data transfer
Fixed transfer/streaming/streaming-03-kafka-broker/5-negotiate-contract.json file by including the odrl context.
Fixed transfer/streaming/streaming-023-kafka-broker/6-transfer.json file by including the transfer type and the private properties
The transfer process was not working correctly because the transfer type was missing. Including the transfer type explicitly defines the expected data exchange format, allowing the transfer to proceed without errors.
@ndr-brt
Closes #372
> fix: sample streaming-03 kafka broker sample

- system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer04eventConsumerTest.java
- transfer/transfer-00-prerequisites/connector/build.gradle.kts
- transfer/transfer-01-negotiation/README.md
- transfer/transfer-02-provider-push/README.md
- transfer/transfer-03-consumer-pull/provider-proxy-data-plane/build.gradle.kts
- transfer/transfer-04-event-consumer/README.md
- transfer/transfer-04-event-consumer/listener/src/main/java/org/eclipse/edc/sample/extension/listener/TransferProcessStartedListener.java
Remove `public-api` module from "prerequisites" connector
Avoid conflicts with the proxy extension
- had to fix transfer-04 because it was relying on transfer-03 but the provider was the one without the http proxy capabilities, now transfer-04 is based on transfer-02 (push)
_Please @-mention the committer that will sponsor your feature_.
Closes #376 
> fix: sample 03

- basic/basic-01-basic-connector/README.md
The PR changes the README of the _basic-01-basic-connector_ sample to correct the statement about the dependencies loaded via the grade build file.
Further it sets the log level to DEBUG to achieve the expected output with `--log-level=DEBUG`  
Update the sample description to meet the current version and requirement through the change in log-level handling.
> chore: update README for basic-01-basic-connector

- policy/policy-01-policy-enforcement/README.md
This PR updates the policy-01-policy-enforcement/README.md file to fix and clarify the instructions for running and testing the provided code.
While going through the README to test the code, I noticed that some of the final instructions **(Bind the constraint to the cataloging scope)**  didn’t work as expected. After a bit of trial and error, I found that a few parts were either outdated or incorrect.
This is what i found:
1. The CATALOGING_SCOPE doesn’t seem to exist. The actual constant is CATALOG_SCOPE, and the correct context class to use with policyEngine.registerFunction is CatalogPolicyContext.class.
2. The import statement for the correct constant (CATALOG_SCOPE) was missing.
3. A code change in LocationConstraintFunction.java is also needed. This wasn't mentioned in the README, …
> fix(policy/enforcement): update README for policy 01

- advanced/advanced-02-custom-runtime/build.gradle.kts
- basic/basic-01-basic-connector/README.md
- basic/basic-01-basic-connector/build.gradle.kts
- basic/basic-02-health-endpoint/build.gradle.kts
- basic/basic-03-configuration/build.gradle.kts
- federated-catalog/fc-01-embedded/fc-connector/build.gradle.kts
- federated-catalog/fc-02-standalone/standalone-fc/build.gradle.kts
- federated-catalog/fc-03-static-node-directory/embedded-fc-with-node-resolver/build.gradle.kts
- federated-catalog/fc-03-static-node-directory/standalone-fc-with-node-resolver/build.gradle.kts
- policy/policy-01-policy-enforcement/policy-enforcement-consumer/build.gradle.kts
- policy/policy-01-policy-enforcement/policy-enforcement-provider/build.gradle.kts
- transfer/transfer-00-prerequisites/connector/build.gradle.kts
- transfer/transfer-03-consumer-pull/provider-proxy-data-plane/build.gradle.kts
- transfer/transfer-04-event-consumer/consumer-with-listener/build.gradle.kts
- transfer/transfer-05-file-transfer-cloud/cloud-transfer-consumer/build.gradle.kts
- transfer/transfer-05-file-transfer-cloud/cloud-transfer-provider/build.gradle.kts
- transfer/transfer-06-kafka-broker/kafka-runtime/build.gradle.kts
Add missing `duplicatesStrategy = DuplicatesStrategy.INCLUDE` setting for shadow plugin that become mandatory to permit proper service file merging.
_Briefly state why the change was necessary._
_Please @-mention the committer that will sponsor your feature_.
Closes #459 
> fix: add missing shadow jar config
